# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeserver_lua', '0003_auto_20170918_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidcontrol',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'\xe7\xbb\x93\xe6\x9d\x9f\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='notes',
            field=models.TextField(blank=True, default=b'', verbose_name=b'\xe6\xb3\xa8\xe9\x87\x8a\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name=b'\xe5\xbc\x80\xe5\xa7\x8b\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'\xe8\xae\xbe\xe5\xa4\x87\xe5\xba\x8f\xe5\x88\x97\xe5\x8f\xb7'),
        ),
    ]
