# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeserver_lua', '0004_auto_20170918_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidcontrol',
            name='notes',
            field=models.TextField(blank=True, default=b'', verbose_name=b'\xe9\x99\x84\xe5\x8a\xa0\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
    ]
