# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeserver_lua', '0005_auto_20170918_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidcontrol',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='notes',
            field=models.TextField(blank=True, default=b'', verbose_name='\u9644\u52a0\u4fe1\u606f'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='uuidcontrol',
            name='uuid',
            field=models.CharField(max_length=100, unique=True, verbose_name='\u8bbe\u5907\u5e8f\u5217\u53f7'),
        ),
    ]
