# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeserver_lua', '0008_auto_20170919_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='uuidcontrol',
            name='devid',
            field=models.CharField(default='', max_length=100, verbose_name='\u56fa\u4ef6\u5e8f\u5217\u53f7'),
        ),
    ]
