# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upgradeserver_lua', '0010_auto_20170919_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacontrol',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
    ]
